baseurl = "https://oayul.github.io/"
languageCode = "en-us"
title = "Computer	Vision	for	Microscopy	Image	Analysis (CVMI)"
MetaDataFormat = "yaml"

[params]

[[menu.main]]
    name = "Submission"
	weight = 6
	url = "http://cvpr2016.thecvf.com/submission/timeline"
